import { useState } from 'react'

interface Planet {
  id: string
  name: string
  icon: string
  color: string
  fate: string
  verdict: 'dead' | 'dying' | 'alive' | 'hostile'
  verdictLabel: string
  temperature: string
  atmosphere: string
  water: string
  magneticField: string
  whatKilledIt: string
  whenItDied: string
  howItDied: string[]
  couldItHaveBeenEarth: string
  lifeChance: string
  lifeChancePct: number
  surfaceCondition: string
  keyFact: string
  earthComparison: string
}

const PLANETS: Planet[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    icon: '⚫',
    color: '#94a3b8',
    fate: 'Stripped Bare',
    verdict: 'dead',
    verdictLabel: 'Dead',
    temperature: '-180°C to +430°C (swings of 600°C)',
    atmosphere: 'Almost none — trace exosphere only',
    water: 'Ice in permanently shadowed craters only',
    magneticField: 'Weak — 1% of Earth\'s',
    whatKilledIt: 'Too small, too close to the Sun',
    whenItDied: 'Never truly "lived" — never had the conditions',
    howItDied: [
      'Too small to gravitationally hold an atmosphere — solar wind stripped it',
      'Extremely slow rotation means one side bakes, the other freezes',
      'No plate tectonics — no way to recycle carbon or regulate temperature',
      'Close proximity to Sun means extreme solar radiation bombardment',
    ],
    couldItHaveBeenEarth: 'No. Even in the best scenario, Mercury\'s mass (5.5% of Earth) means it can\'t hold an atmosphere or generate enough internal heat for volcanism.',
    lifeChance: 'Near zero',
    lifeChancePct: 2,
    surfaceCondition: 'Barren, cratered rock. No wind, no weather. Silence.',
    keyFact: 'Mercury\'s surface temperature swings 600°C between day and night — the largest temperature swing of any planet.',
    earthComparison: 'Mercury has no atmosphere, no water cycle, no magnetic shield. Earth has all three.'
  },
  {
    id: 'venus',
    name: 'Venus',
    icon: '🌕',
    color: '#f97316',
    fate: 'Runaway Greenhouse Hell',
    verdict: 'hostile',
    verdictLabel: 'Hostile',
    temperature: '+465°C (hotter than Mercury)',
    atmosphere: '96% CO₂, 90× Earth\'s pressure — equivalent to 900m underwater',
    water: 'None on surface. Sulfuric acid clouds.',
    magneticField: 'Almost none',
    whatKilledIt: 'Runaway greenhouse effect',
    whenItDied: '~700 million years ago (massive volcanic resurfacing)',
    howItDied: [
      'Once may have had oceans and a habitable climate for 2-3 billion years',
      'Slow rotation (243 Earth days) meant uneven heating and climate instability',
      'Massive volcanic eruptions released CO₂, triggering runaway greenhouse effect',
      'Without a magnetic field, solar wind stripped away the water vapor',
      'Surface reached 465°C — lead melts here',
    ],
    couldItHaveBeenEarth: 'Yes — Venus may have been habitable for billions of years. It\'s almost Earth\'s twin in size and composition. Climate models suggest ancient Venus had oceans.',
    lifeChance: 'Possible in cloud layers at 50km altitude (50°C, 1 atm pressure)',
    lifeChancePct: 12,
    surfaceCondition: 'Crushing pressure, scorching heat, sulfuric acid rain that evaporates before it hits the ground.',
    keyFact: 'Venus rotates so slowly that a day on Venus (243 Earth days) is longer than a year on Venus (225 Earth days).',
    earthComparison: 'Venus is Earth\'s evil twin — same size, same composition, but a totally different fate. The difference: magnetic field and distance from Sun.'
  },
  {
    id: 'earth',
    name: 'Earth',
    icon: '🌍',
    color: '#22c55e',
    fate: 'The Miracle',
    verdict: 'alive',
    verdictLabel: 'Alive',
    temperature: '-89°C to +56°C (average +15°C)',
    atmosphere: '78% N₂, 21% O₂, 1% Ar — life-generated',
    water: '71% surface water, global water cycle',
    magneticField: 'Strong — deflects solar wind completely',
    whatKilledIt: 'Nothing — yet',
    whenItDied: 'Not dead — but will become uninhabitable in ~1 billion years',
    howItDied: [
      'In 1 billion years, the Sun brightens 10% — oceans begin evaporating',
      'In 5 billion years, the Sun becomes a red giant and swallows Earth',
      'For now, the perfect combination of factors makes life possible',
      'Plate tectonics recycles carbon (Venus has none)',
      'Moon stabilizes axial tilt, preventing extreme climate swings',
    ],
    couldItHaveBeenEarth: 'Earth IS Earth. The question is: how many other Earths are out there?',
    lifeChance: '100% — 4 billion years of confirmed life',
    lifeChancePct: 100,
    surfaceCondition: 'Liquid water, breathable air, stable temperatures. The only known place in the universe with confirmed life.',
    keyFact: 'Earth\'s magnetic field, generated by a liquid iron outer core, is the invisible shield that makes all life possible. Without it, solar wind would strip our atmosphere within millions of years.',
    earthComparison: 'Earth is the baseline. Every other planet is compared to Earth for a reason.'
  },
  {
    id: 'mars',
    name: 'Mars',
    icon: '🔴',
    color: '#ef4444',
    fate: 'Slowly Dying',
    verdict: 'dying',
    verdictLabel: 'Dying',
    temperature: '-125°C to +20°C (average -60°C)',
    atmosphere: '95% CO₂, but only 0.6% of Earth\'s pressure — essentially vacuum',
    water: 'Frozen in polar ice caps and underground. Liquid water existed 3.5B years ago.',
    magneticField: 'None — lost it ~4 billion years ago',
    whatKilledIt: 'Loss of magnetic field → atmosphere stripped by solar wind',
    whenItDied: 'Lost habitability ~3.5 billion years ago',
    howItDied: [
      'Mars is too small — its iron core cooled and solidified, stopping the dynamo',
      'Without a magnetic field, solar wind stripped the atmosphere over millions of years',
      'Without atmosphere, liquid water is impossible on the surface',
      'Ancient Mars had rivers, lakes, and possibly an ocean — all gone',
      'Giant volcanic province Tharsis may have triggered the atmospheric loss',
    ],
    couldItHaveBeenEarth: 'Mars was likely habitable for 500 million to 1 billion years. Ancient Mars may have had life. We haven\'t found it — yet.',
    lifeChance: 'Ancient life: possible. Current life: subsurface only',
    lifeChancePct: 35,
    surfaceCondition: 'Cold desert. Thin atmosphere. Radiation bombardment. Massive dust storms covering the entire planet.',
    keyFact: 'Mars has the largest volcano in the solar system (Olympus Mons, 21 km high) and the longest canyon (Valles Marineris, 4,000 km). Both formed when Mars was geologically active.',
    earthComparison: 'Mars is what Earth could become if it lost its magnetic field. In 3.5 billion years, the story of Mars could be the future story of Earth.'
  },
  {
    id: 'europa',
    name: 'Europa (Moon of Jupiter)',
    icon: '🧊',
    color: '#06b6d4',
    fate: 'Hidden Ocean World',
    verdict: 'alive',
    verdictLabel: 'Possibly Alive',
    temperature: '-160°C surface, possibly warm near hydrothermal vents',
    atmosphere: 'Thin oxygen atmosphere — produced by radiation splitting water ice',
    water: 'Global subsurface ocean, 100 km deep — more liquid water than all Earth\'s oceans combined',
    magneticField: 'Induced by Jupiter\'s powerful magnetic field',
    whatKilledIt: 'Nothing — may still be active and possibly habitable',
    whenItDied: 'Not dead — the subsurface ocean has been liquid for billions of years',
    howItDied: [
      'Europa is NOT dead — it\'s one of our best candidates for extraterrestrial life',
      'Tidal heating from Jupiter keeps the subsurface ocean liquid',
      'Hydrothermal vents may exist on the ocean floor — like Earth\'s deep sea vents where life thrives',
      'Surface is coated in water ice criss-crossed by cracks from tidal flexing',
    ],
    couldItHaveBeenEarth: 'Europa may be better than Earth for life in some ways — its ocean has been stable for billions of years, protected from radiation by 10 km of ice.',
    lifeChance: 'High for microbial life — best bet in the solar system after Earth',
    lifeChancePct: 65,
    surfaceCondition: 'Smooth ice shell with reddish cracks (possibly salts from below). Icy plains, no mountains, no craters larger than a few km (the ice reshapes itself).',
    keyFact: 'NASA\'s Europa Clipper spacecraft launched in October 2024 and will arrive at Europa in 2030. It will make 49 close flybys to search for signs of habitability.',
    earthComparison: 'Europa proves that life doesn\'t need sunlight — just liquid water, chemistry, and energy. This fundamentally changes where we look for life.'
  },
  {
    id: 'titan',
    name: 'Titan (Moon of Saturn)',
    icon: '🟠',
    color: '#f59e0b',
    fate: 'Alien Earth',
    verdict: 'hostile',
    verdictLabel: 'Alien Life?',
    temperature: '-179°C',
    atmosphere: '95% nitrogen — denser than Earth\'s, the only other thick N₂ atmosphere in the solar system',
    water: 'No liquid water. Lakes of liquid methane and ethane instead.',
    magneticField: 'None — protected by Saturn\'s magnetosphere',
    whatKilledIt: 'Too cold for water-based life — but methane-based life is theoretically possible',
    whenItDied: 'Not "dead" — just very different. May support exotic life.',
    howItDied: [
      'Titan is too cold (-179°C) for liquid water on the surface',
      'Instead of a water cycle, Titan has a methane cycle — methane rain, rivers, lakes, seas',
      'The atmosphere is rich in organic molecules — the building blocks of life',
      'Theorized: cell membranes made of acrylonitrile instead of lipids could survive in methane',
      'NASA\'s Dragonfly mission (2028 launch) will fly a helicopter-drone across Titan',
    ],
    couldItHaveBeenEarth: 'Titan could support life — just not life as we know it. Methane-based life would be so different we might not recognize it.',
    lifeChance: 'Low but non-zero for exotic methane-based life',
    lifeChancePct: 20,
    surfaceCondition: 'Orange haze. Methane seas in the north. Dunes of organic material. Rivers carved by methane rain. Earth-like landscape, alien chemistry.',
    keyFact: 'Titan is the only moon with a thick atmosphere and the only place besides Earth with stable liquid on its surface — just methane instead of water.',
    earthComparison: 'Titan looks disturbingly like early Earth in some ways — thick nitrogen atmosphere, weather, rivers, seas — just 200°C colder and with the wrong liquid.'
  },
]

const VERDICT_COLORS: Record<Planet['verdict'], string> = {
  dead: '#6b7280',
  dying: '#ef4444',
  alive: '#22c55e',
  hostile: '#f97316',
}

export default function PlanetaryFates() {
  const [selected, setSelected] = useState<Planet>(PLANETS[3])

  return (
    <div className="space-card p-6">
      <h2 className="text-2xl font-bold text-white mb-1">What Killed Each Planet</h2>
      <p className="text-gray-400 text-sm mb-5">A forensic investigation into why Venus became hell, Mars became a desert, and Earth got lucky</p>

      {/* Planet selector */}
      <div className="grid grid-cols-3 md:grid-cols-6 gap-2 mb-6">
        {PLANETS.map(p => (
          <button
            key={p.id}
            onClick={() => setSelected(p)}
            className="p-3 rounded-xl transition-all text-center"
            style={{
              background: selected.id === p.id ? p.color + '20' : 'rgba(15,23,42,0.5)',
              border: `1px solid ${selected.id === p.id ? p.color + '60' : 'rgba(255,255,255,0.06)'}`,
            }}
          >
            <div className="text-2xl mb-1">{p.icon}</div>
            <div className="text-xs font-bold" style={{ color: selected.id === p.id ? p.color : '#9ca3af' }}>{p.name}</div>
            <div className="mt-1 text-[9px] px-1.5 py-0.5 rounded-full font-bold inline-block"
              style={{ background: VERDICT_COLORS[p.verdict] + '25', color: VERDICT_COLORS[p.verdict] }}>
              {p.verdictLabel}
            </div>
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Left: stats */}
        <div className="space-y-3">
          <div className="rounded-xl p-4" style={{ background: selected.color + '12', border: `1px solid ${selected.color}35` }}>
            <div className="flex items-center gap-3 mb-3">
              <span className="text-4xl">{selected.icon}</span>
              <div>
                <h3 className="text-xl font-bold text-white">{selected.name}</h3>
                <span className="text-sm font-bold px-2 py-0.5 rounded-full" style={{ background: VERDICT_COLORS[selected.verdict] + '30', color: VERDICT_COLORS[selected.verdict] }}>
                  {selected.fate}
                </span>
              </div>
            </div>

            {/* Life chance bar */}
            <div className="mb-3">
              <div className="flex justify-between text-xs mb-1">
                <span className="text-gray-400">Life Probability</span>
                <span className="font-bold" style={{ color: selected.lifeChancePct > 50 ? '#22c55e' : selected.lifeChancePct > 15 ? '#f97316' : '#ef4444' }}>
                  {selected.lifeChancePct}%
                </span>
              </div>
              <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                <div className="h-full rounded-full transition-all duration-700"
                  style={{ width: `${selected.lifeChancePct}%`, background: selected.lifeChancePct > 50 ? '#22c55e' : selected.lifeChancePct > 15 ? '#f97316' : '#ef4444' }} />
              </div>
              <div className="text-gray-500 text-xs mt-1">{selected.lifeChance}</div>
            </div>

            {[
              { label: '🌡️ Temperature', val: selected.temperature },
              { label: '💨 Atmosphere', val: selected.atmosphere },
              { label: '💧 Water', val: selected.water },
              { label: '🧲 Magnetic Field', val: selected.magneticField },
            ].map(s => (
              <div key={s.label} className="text-xs mb-1.5">
                <span className="text-gray-500">{s.label}: </span>
                <span className="text-gray-300">{s.val}</span>
              </div>
            ))}
          </div>

          <div className="bg-gray-800/60 rounded-xl p-4">
            <div className="text-gray-400 text-xs uppercase font-semibold mb-2">Surface Today</div>
            <p className="text-gray-300 text-sm leading-relaxed">{selected.surfaceCondition}</p>
          </div>

          <div className="bg-gray-800/60 rounded-xl p-4">
            <div className="text-gray-400 text-xs uppercase font-semibold mb-2">vs Earth</div>
            <p className="text-gray-300 text-sm leading-relaxed">{selected.earthComparison}</p>
          </div>
        </div>

        {/* Right: cause of death */}
        <div className="space-y-3">
          <div className="rounded-xl p-4" style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)' }}>
            <div className="text-red-400 text-xs uppercase font-semibold mb-1">Cause of Death / Fate</div>
            <div className="font-bold text-white mb-2">{selected.whatKilledIt}</div>
            <div className="text-gray-500 text-xs mb-3">{selected.whenItDied}</div>
            <ul className="space-y-1.5">
              {selected.howItDied.map((d, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-gray-300">
                  <span className="text-red-400 flex-shrink-0 mt-0.5">▸</span>
                  {d}
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-xl p-4" style={{ background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.2)' }}>
            <div className="text-indigo-400 text-xs uppercase font-semibold mb-2">Could It Have Been Earth?</div>
            <p className="text-gray-300 text-sm leading-relaxed">{selected.couldItHaveBeenEarth}</p>
          </div>

          <div className="rounded-xl p-4" style={{ background: 'rgba(251,191,36,0.08)', border: '1px solid rgba(251,191,36,0.2)' }}>
            <div className="text-amber-400 text-xs uppercase font-semibold mb-2">🔑 Key Fact</div>
            <p className="text-amber-100/80 text-sm leading-relaxed">{selected.keyFact}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
